### ISSUE TITLE
Self-host is exposed to the internet

### ISSUE THREAD

**Issue by gibberishgithub** [merlinfuchs/embed-generator#123]
I'm self-hosting because I just want to be able to have the premium features for myself, I configured it to be "premium" by default.

Problems:
- Local environment means the button responses won't work.
- Placing an additional OAUTH login-wall from a provider like Google in front of the production environment's public domain means the button responses won't work.
- Anyone who can figure out my domain is able to access the website and use the premium features, including being able to send messages through webhooks without Discord login.
- Custom-bot doesn't work with public environment.

Solutions:
- Restrict access to only the server the bot is in.
- Require bot to be in the server if wanting to use a webhook with limited features.
- Optional env variable to specify; User ID so that only the owner Discord ID can use it once signed in, Guild ID.

**Comment by merlinfuchs** [comment]
You realise that you are openly asking me how to circumvent paying for the premium features? 😅 

> Local environment means the button responses won't work.

You can use buttons just fine without exposing the service to the internet. The bot receives interactions over the gateway unless you have a custom bot configured.

**Comment by gibberishgithub** [comment]
I thought I needed the second custom bot to have the buttons because I saw a non-open source project work in this way (has some features that this project doesn't but this project overall does everything better and has unique features the other doesn't have) and the fact this project needs only ONE BOT, is a huge bonus, I deleted the custom bot and now I don't have to have my instance of embed generator exposed to the internet, and the AI still works :)

**Comment by merlinfuchs** [comment]
Glad it works now :) Out of curiosity what is the other project you were talking about?

**Comment by gibberishgithub** [comment]
They are very minor features, and they are missing a lot of stuff Embed Generator has.

DotNotify - not open-source, schedules announcements / reminder embeds/messages with options:

- Hourly
- Daily
- Weekly
- Bi-weekly
- Monthly
- One-time

Then there's DiscoHook which has the main-site open-sourced, no clue about the "helper" bot that's mandatory and you also need the chrome extension, less features then embed-generator, and it requires a second helper bot if wanting to add extra functions to embeds, most notable features are with second bot + extension:

- Reaction-emoji support
- Can also schedule messages but not as great as DotNotify which also allows you to implement UNIX timestamps instead of leaving the editor and going to a UNIX generator
- visually see the roles / channels / users (extension needed)

Overall, the other bots out there, are severely lacking A LOT OF FEATURES that your project has and with the exception of DotNotify, the setup process is annoying because of it requiring 3 things, which I have now seen is not necessary:

- Main bot
- Second bot
- Browser extension

**Comment by merlinfuchs** [comment]
Thanks for the info! Always good to know which other options are out there and I haven't heard of DotNotify before 👍 

Implementing scheduled messages / announcements is on my list #108 

If you want to support the development of Embed Generator consider subscribing to Premium even if you self host :)

**Comment by merlinfuchs** [comment]
@gibberishgithub Scheduled messages are now available :)
