### ISSUE TITLE
Docker-compose file does not work

### ISSUE THREAD

**Issue by GameAreaCZ** [merlinfuchs/embed-generator#140]
"Failed to check if bucket images exists: Get \"http://localhost:9000/images/?location=\": dial tcp 127.0.0.1:9000: connect: connection refused

**Comment by GameAreaCZ** [comment]
And the adress:5172 is not working

**Comment by merlinfuchs** [comment]
I have updated the docker-compose file in the readme to include minio. That should fix your problem.

**Comment by GameAreaCZ** [comment]
Thank you, but still same error:

embedg_1    | Using config file: /root/config.yaml
embedg_1    | Using config file: /root/config.yaml
embedg_1    | 3:50PM WRN Already at the correct version, migration was skipped entry=migrate host=73cb07c6daf8 operation=up store=postgres
embedg_1    | Using config file: /root/config.yaml
embedg_1    | 3:50PM FTL Failed to initialize blob store error="Failed to check if bucket images exists: Get \"http://localhost:9000/images/?location=\": dial tcp 127.0.0.1:9000: connect: connection refused" host=73cb07c6daf8

**Comment by merlinfuchs** [comment]
Just tried myself and the updated docker-compose file works fine. Make sure you run `docker-compose down` and then `docker-compose up` with the new file.

**Comment by GameAreaCZ** [comment]
I tried it, I even make a clean VM installation to try, but same error as on the host one.

**Comment by merlinfuchs** [comment]
The docker file at https://github.com/merlinfuchs/embed-generator/blob/main/docker-compose.yaml does definitely work, the one in the README I have to double check

**Comment by merlinfuchs** [comment]
The one in the README should now also work.

**Comment by GameAreaCZ** [comment]
Thank you, it is working now, but I am trying to localy login via the callback and I do not understand in the readme config there is:
http://localhost:5173/api what is the 5173 port? Is it running on that port something? Because when I add it as a callback

http://localhost:5173/api/auth/callback .. it does not work. When I add callback with port 8080 then it shows the authorize page from discord, but when I click on login it just looping that authorize discord page all over agay.

**Comment by merlinfuchs** [comment]
I sadly can't help you with every specific problem here. The docker-compose should work as long as you configure it correctly with the `config.yaml` file.
I think you can just ignore the `FATAL: role "root" does not exist`.

**Comment by GameAreaCZ** [comment]
Thank you, but unfortunately no :(

embedg_1    | 6:47PM ERR Failed to authenticate with code error="Failed to exchange token: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\": \"invalid_client\"}" host=9cd724d21c36

**Comment by GameAreaCZ** [comment]
Can you please help me how I can try to give myself the premium features? @merlinfuchs

**Comment by merlinfuchs** [comment]
> Can you please help me how I can try to give myself the premium features?

There is enough information in the README of this repository to figure this out by yourself. I will not give you a step-by-step tutorial for this.
