### ISSUE TITLE
Question and Suggestion

### ISSUE THREAD

**Issue by ual1n** [merlinfuchs/embed-generator#144]
Well, I'm unsure about something and I'd also like to suggest a few. 
My question is, in the paid version can I only change the banner and image of the bot that appears with the message, or can I change the Embed Generator bot as well? So I thought it sent a message with a fictitious bot, just with a photo and banner, and the paid version was for customizing the main bot Embed Generator.

As a suggestion, I would like the bot to be able to add roles by reaction, and also auto-add reactions to messages when sending.

**Comment by merlinfuchs** [comment]
The main purpose of custom bots is to change the appearance on response messages to interactive components. Usually, these have the default name and avatar of the bot, but with a custom bot you can customize them.
Additionally the custom bot allows you to create custom commands!

**Comment by ual1n** [comment]
Thanks for the answer. I had inserted an image through the dashboard, but the photo was not updated when I sent the message on the test channel, so I wanted to know if the premium was to customize this profile that appears in the message, or customize the main BOT Embed Generator.

**Comment by merlinfuchs** [comment]
> I had inserted an image through the dashboard, but the photo was not updated when I sent the message on the test channel

This was most likely a temporary Discord issue. The avatar your set I the dashboard should be the one appearing on the message.
