### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by ramonor** [merlinfuchs/embed-generator#145]
FTL Failed to initialize blob store error="Failed to check if bucket images exists: Get \"http://localhost:9000/images/?location=\": dial tcp [::1]:9000: connectex: No connection could be done because the target machine actively refused them."

**Comment by merlinfuchs** [comment]
Make sure you are using the most recent docker-compose file.

**Comment by ramonor** [comment]
I'm using Windows

**Comment by merlinfuchs** [comment]
Are you running all services defined in the docker-compose file yourself? Embed Generator depends on Postgres and an S3 store (e.g. minio) to work. The error you are getting looks like you don't have an S3 store configured.
