### ISSUE TITLE
Invalid image URL whan use GIF or PNG in AUTHOR ICON URL

### ISSUE THREAD

**Issue by Vlad2IO** [merlinfuchs/embed-generator#39]
Invalid image URL whan use GIF or PNG in AUTHOR ICON URL

![This is an image](https://i.imgur.com/7eAd4mB.png)

**Comment by Vlad2IO** [comment]
Example URL: https://emoji.discadia.com/emojis/424211db-c7f6-453a-a2b6-b05b66a71ee0.GIF
Remove case sensitivity please!

**Comment by Pohy101** [comment]
![browser_SFA3YjTUXe](https://user-images.githubusercontent.com/45663529/202226673-0cd75ec8-009a-4fd7-ab94-156dd929d806.gif)
It's about your link.
Everything works.

**Comment by Pohy101** [comment]
> Пример URL: https://emoji.discadia.com/emojis/424211db-c7f6-453a-a2b6-b05b66a71ee0.GIF Пожалуйста, уберите чувствительность к регистру!
![browser_SFA3YjTUXe](https://user-images.githubusercontent.com/45663529/202231371-0ff882bb-7218-4e8d-a45d-0fe376e15eb4.gif)
It's about your link.
Everything works.

**Comment by Pohy101** [comment]
> Пример URL: https://emoji.discadia.com/emojis/424211db-c7f6-453a-a2b6-b05b66a71ee0.GIF Пожалуйста, уберите чувствительность к регистру!

It's about your link.
Everything works.
![browser_SFA3YjTUXe](https://user-images.githubusercontent.com/45663529/202231560-657768a4-a2bf-448e-bcd0-acb917d60b21.gif)

**Comment by merlinfuchs** [comment]
it's currently case sensitive, so .gif will work but .GIF won't

**Comment by merlinfuchs** [comment]
The URL requirement for images has now been relaxed to accept all kinds of URLs. There is sadly no good way to validate that an URL is a valid image URL.
