### ISSUE TITLE
[Feature Request] "Copy JSON" button

### ISSUE THREAD

**Issue by couleurm** [merlinfuchs/embed-generator#40]
Hi, could such a button be placed like in the screenshot or inside of the "View JSON" dialog? Thank you!
![image](https://user-images.githubusercontent.com/82747632/216054522-aa990077-5cf1-4ad9-9256-0b08e45fe82f.png)

**Comment by Pohy101** [comment]
What is the difficulty of copying JSON yourself?

**Comment by couleurm** [comment]
> What is the difficulty of copying JSON yourself?

I copy quite a lot so a button to save me a few clicks would help me, I understand that it's not really that much of a need for others 👍

**Comment by Pohy101** [comment]
CTRL+A --> CTRL+C and copied all the text, no matter how much it was there,
