### ISSUE TITLE
Is it possible to create a thread?

### ISSUE THREAD

**Issue by lucasvazq** [merlinfuchs/embed-generator#88]
My users have to comment on a thread for a bot to register them.

Right now that thread is in my name, while the welcome is given by the bot.

![Screenshot from 2023-05-30 11-15-32](https://github.com/merlinfuchs/embed-generator/assets/38964964/04aedf62-16d3-489b-b126-47945428eee6)

**Comment by lucasvazq** [comment]
It is not possible even hitting the discord API directly

**Comment by merlinfuchs** [comment]
Sorry, I didn't see your issue here. You should be able to start a thread under the bot message yourself 🤔
