### ISSUE TITLE
Direkt Link must contain http or https

### ISSUE THREAD

**Issue by NUCL3ARN30N** [merlinfuchs/embed-generator#94]
When creating a Row > Button > Style = Direct Link the Web App tells you that it is necessary to add an http:// or https:// within the URL.
Because of this feature it is impossible to add URLs which are redirecting to specific apps.
Example steam://connect/ip 
The example URL is trying to connect you to a game server on steam. 
The error message displayed says "Invalid URL"

**Comment by Pohy101** [comment]
This is a discord limitation, not a bot.

**Comment by merlinfuchs** [comment]
The only way to do this is to setup a webserver that redirects to the application link so you can link to the webserver inside Discord.
